### ISSUE TITLE
Loggin

### ISSUE THREAD

**Issue by NBSUKLTD** [git-temak/auto-update-post-date#3]
Hey,

Nice idea for a plugin, what is the best way to keep tracks of activity? We have over 7,000 products posts and pages. 

it would be a good to have a stat counter of sorts which shows its progress over time also to ensure its actually running.

**Comment by git-temak** [comment]
Hi @NBSUKLTD i'll be adding a log option in an update coming in some weeks time. I'll let you know once its done so you can check if that fits your needs.

**Comment by git-temak** [comment]
Hi @NBSUKLTD you can download the updated version of the plugin here with the log feature added https://github.com/git-temak/auto-update-post-date/archive/refs/heads/main.zip

The plugin itself will be updated on the WP directory but wanted to send the latest version to you first. Let me know if that's all working well for you
